server:
   port: 8084
   contextPath: /
   resetCache: true
spring:
  redis:
    host: localhost
    port: 6379

# DATASOURCE
jdbc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://test.haifuc.cn/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password: lucifer-HFC-20170501
#jdbc-shop:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://test.haifuc.cn/t-mf?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password: lucifer-HFC-20170501

#jdbc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password:
jdbc-shop:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/t-mf?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password:


# MyBatis

mybatis:
    typeAliasesPackage: com.lucifer.model
    mapperLocations: classpath:/sqlmaps/*.xml
    configLocation: classpath:/mybatis-config.xml

qiniu:
  accessKey: eeYtcWvGPXqjEiTIxDljeVu8qxFpwdXOvGo4PURq
  secretKey: LHkSG-HRLccuUYSgb-TX0ZcDrsyUMEzSg6Z3GG6G
  publicBucket: shop-lucifer
  url: http://ojvbqldpg.bkt.clouddn.com/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb
solr:
  url:
    news: http://test.haifuc.cn:8983/solr/news
    artist: http://test.haifuc.cn:8983/solr/artist
    appreciate: http://test.haifuc.cn:8983/solr/appreciate
sms:
  sendCodeUrl: https://api.netease.im/sms/sendcode.action
  appKey: 80f0cbe03428deb5f520005694aeffdd
  appSecret: ef2c21102cb8
  verifyCodeUrl: https://api.netease.im/sms/verifycode.action





